import '../models/dhikr_item.dart';

final List<DhikrItem> kSeedItems = [
  DhikrItem(id: 'b1', category: 'morning', type: 'text', target: 'مرة واحدة', source: 'صحيح مسلم', createdAt: 0, isBuiltin: true,
      title: 'أصبحنا وأصبح الملك',
      text: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ.'),
  DhikrItem(id: 'b2', category: 'morning', type: 'text', target: 'مرة واحدة', source: 'سنن الترمذي', createdAt: 0, isBuiltin: true,
      title: 'اللهم بك أصبحنا',
      text: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ.'),
  DhikrItem(id: 'b3', category: 'morning', type: 'text', target: 'مرة واحدة', source: 'البقرة 255', createdAt: 0, isBuiltin: true,
      title: 'آية الكرسي',
      text: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ، لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ، لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ، مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ، يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ، وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ، وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ، وَلَا يَئُودُهُ حِفْظُهُمَا، وَهُوَ الْعَلِيُّ الْعَظِيمُ.'),
  DhikrItem(id: 'b4', category: 'morning', type: 'text', target: '٧ مرات', source: 'سنن أبي داود', createdAt: 0, isBuiltin: true,
      title: 'حسبي الله',
      text: 'حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ.'),
  DhikrItem(id: 'b5', category: 'morning', type: 'text', target: '١٠٠ مرة', createdAt: 0, isBuiltin: true,
      title: 'الاستغفار',
      text: 'أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ.'),
  DhikrItem(id: 'b6', category: 'evening', type: 'text', target: 'مرة واحدة', source: 'صحيح مسلم', createdAt: 0, isBuiltin: true,
      title: 'أمسينا وأمسى الملك',
      text: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ.'),
  DhikrItem(id: 'b7', category: 'evening', type: 'text', target: '٣ مرات', source: 'سنن الترمذي', createdAt: 0, isBuiltin: true,
      title: 'التعوذ بكلمات الله',
      text: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ.'),
  DhikrItem(id: 'b8', category: 'evening', type: 'text', target: 'مرة واحدة', source: 'البقرة 255', createdAt: 0, isBuiltin: true,
      title: 'آية الكرسي مساءً',
      text: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ... وَهُوَ الْعَلِيُّ الْعَظِيمُ.'),
  DhikrItem(id: 'b9', category: 'sleep', type: 'text', target: 'مرة واحدة', source: 'صحيح البخاري', createdAt: 0, isBuiltin: true,
      title: 'باسمك اللهم أموت وأحيا',
      text: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا.'),
  DhikrItem(id: 'b10', category: 'sleep', type: 'text', target: 'مرة واحدة', source: 'متفق عليه', createdAt: 0, isBuiltin: true,
      title: 'اللهم أسلمت نفسي إليك',
      text: 'اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ، لَا مَلْجَأَ وَلَا مَنْجَا مِنْكَ إِلَّا إِلَيْكَ.'),
  DhikrItem(id: 'b11', category: 'sleep', type: 'text', target: '٣٣+٣٣+٣٤', source: 'تسبيح فاطمة', createdAt: 0, isBuiltin: true,
      title: 'تسبيح فاطمة',
      text: 'سُبْحَانَ اللَّهِ (٣٣)، الْحَمْدُ لِلَّهِ (٣٣)، اللَّهُ أَكْبَرُ (٣٤).'),
  DhikrItem(id: 'b12', category: 'salawat', type: 'text', target: 'بلا حصر', createdAt: 0, isBuiltin: true,
      title: 'الصلاة المختصرة',
      text: 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ.'),
  DhikrItem(id: 'b13', category: 'salawat', type: 'text', target: 'مرة واحدة', source: 'الصلاة الإبراهيمية', createdAt: 0, isBuiltin: true,
      title: 'الصلاة الإبراهيمية',
      text: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ.'),
  DhikrItem(id: 'b14', category: 'full', type: 'text', target: '١٠٠ مرة', createdAt: 0, isBuiltin: true,
      title: 'لا إله إلا الله', text: 'لَا إِلَٰهَ إِلَّا اللَّهُ.'),
  DhikrItem(id: 'b15', category: 'full', type: 'text', target: '١٠٠ مرة', createdAt: 0, isBuiltin: true,
      title: 'الله أكبر', text: 'اللَّهُ أَكْبَرُ.'),
  DhikrItem(id: 'b16', category: 'full', type: 'text', target: '١٠٠ مرة', createdAt: 0, isBuiltin: true,
      title: 'لا حول ولا قوة إلا بالله', text: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ.'),
  DhikrItem(id: 'b17', category: 'full', type: 'text', target: '١٠٠ مرة', source: 'صحيح مسلم', createdAt: 0, isBuiltin: true,
      title: 'سبحان الله وبحمده', text: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ.'),
];
